import {chromium} from 'playwright-core';
import fs from 'fs';
const dir='/private/tmp/claude-501/-Users-saif-pivotprime/67974f8f-8a37-4067-857d-c0792a752d21/scratchpad/tb';
fs.rmSync(dir,{recursive:true,force:true}); fs.mkdirSync(dir,{recursive:true});
const b=await chromium.launch({channel:'chrome'});
const p=await b.newPage({viewport:{width:1440,height:1200}});
await p.goto('http://localhost:3000/services/technology-builds',{waitUntil:'networkidle'});
const sec=p.locator('section').filter({hasText:'What we build'}).last();
await sec.scrollIntoViewIfNeeded(); await p.waitForTimeout(400);
await p.screenshot({path:`${dir}/1440-grid.png`, clip:await sec.boundingBox()});
console.log('labels', await sec.evaluate(el=>[...el.querySelectorAll('h3')].map(h=>h.textContent).join(' | ')));
await b.close();
